name = "free4chat-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "ROOMS_KV"
id = "290b9fb14c1a4505a7aea6cb61ddd1dd"
preview_id = ""

[observability]
enabled = true
